# this is numpy notebook

numpy is numerical python library 

In [1]:
import numpy as np

In [2]:
print("laskhay")

laskhay


In [6]:
li = [1,2,3,4,5]
n = np.array(li)
print(li)
print(n)
print(type(n))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
b = np.array(n, dtype=str)
print(b)

['1' '2' '3' '4' '5']


In [10]:
d = li*3
c = np.array(n*3)
print(c)
print(d)

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [17]:
b = np.ones(6,dtype=int)
b
d = np.ones((3,4),dtype=int)
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
b = np.zeros(5,dtype=int)
b
d = np.zeros((3,4),dtype=int)
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
e = np.full(3,5) #no of elements , the filler digit
print(e)
print("*********")
f = np.full((2,3),5)
print(f)

[5 5 5]
*********
[[5 5 5]
 [5 5 5]]


In [28]:
e = np.empty(3,dtype=int)
e


array([5, 5, 5])

# numpy arrange([start,]stop,[step,]dtype=none)

In [32]:
b = np.arange(10)
print(b)
d = np.arange(2,10)
print(d)
e = np.arange(2,20,2)
print(e)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


# numpy linespace(start,stop,num=50,endpoint=True,restep=False,dtype=None,axis=0)

In [35]:
b = np.linspace(2,10)
print(b)
print(b[1]-b[0])
print(b[3]-b[2])


[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244916


In [38]:
b = np.linspace(2,10,5,dtype=int)
print(b)
d = np.linspace(2,10,5,dtype=int,endpoint=False)
print(d)

[ 2  4  6  8 10]
[2 3 5 6 8]


In [40]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
b = np.eye(3) #you can get 3x4 also but not in identity
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# random function

In [58]:
b = np.random.rand(3)
b

array([0.34674679, 0.42677223, 0.61624193])

In [59]:
b = np.random.rand(2,3)
b

array([[0.10857249, 0.0448479 , 0.33804228],
       [0.00828911, 0.37748852, 0.59545098]])

In [45]:
#b = np.random.rand(size)*10 to get values from 0 to 10 lol
b = np.random.rand(10)*10
b

array([8.78426737, 4.38659374, 5.76042086, 8.64867527, 3.97407901,
       8.50457643, 9.76165763, 6.80472726, 4.09850034, 7.7688392 ])

# slicing in numpy array with comparison to lists

In [76]:
li = [1,2,3,4,5,6]
arr = np.array(li)
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

In [61]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)


(6,)
int32
(4,)


In [63]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)


(4, 4)
int32
(16, 4)


In [65]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [66]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

10
10
10


In [67]:
print(li_2d[1][:3])
print(arr_2d[1][:3])

[5, 6, 7]
[5 6 7]


# accessing columns 

In [71]:
print(li_2d[0:3][2])
print(arr_2d[0:3][2])
print(arr_2d[0:3,2]) # see important

[9, 10, 11, 12]
[ 9 10 11 12]
[ 3  7 11]


In [72]:
print(li_2d[2:4][1:3])
print(arr_2d[2:4,1:3])

[[13, 14, 15, 16]]
[[10 11]
 [14 15]]


# mathematical operations on list vs array

In [77]:
print(li)
li =    [i+1 for i in li]
li

[1, 2, 3, 4, 5, 6]


[2, 3, 4, 5, 6, 7]

In [78]:
print(arr)
arr = arr + 1   # numpy uses vectoization
arr

[1 2 3 4 5 6]


array([2, 3, 4, 5, 6, 7])

we can use addition division mult and sub arr1 + arr2 and so on

In [79]:
print(arr)
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.argmin()) #gives index
print(arr.max())
print(arr.argmax())  #gives index

[2 3 4 5 6 7]
27
4.5
2
0
7
5


also we can use relational and logical operators like arr1 < arr2 will compre all values 1 by 1 or np logical(arr1,arr2)

# boolean indexing in  1D

In [80]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)


['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 8  8 14 16  8 19  2 12]


In [81]:
print(b>10) # true mean ele > 10

[False False  True  True False  True False  True]


In [83]:
#extract all ele > 10
bool_arr = b>10
new_arr = b[bool_arr] #or ome liner new_arr = b[b>10]
print(new_arr)

[14 16 19 12]


In [84]:
new_arr = b[(b>10)&(b<18)]
print(new_arr)

[14 16 12]


In [86]:
c = b
c[:3] = 19 #update elemets of arr with 19 from 0 to 2 but not possible in lists
print(c)
c[c>15] = 100  #only those chages where true i.e where >15
print(c)

[19 19 19 16  8 19  2 12]
[100 100 100 100   8 100   2  12]


# where function

In [88]:
ind = np.where(c==100)
ind

(array([0, 1, 2, 3, 5], dtype=int64),)

# boolean indexing in 2D

In [90]:
a = np.random.randint(1,30,(5,6))
print(a)

[[17 25  5 19 13 22]
 [10 20 15 21 25  4]
 [18  7  5  9 13 26]
 [11 24  6 27 21 28]
 [ 9 12  5 14 13 22]]


In [92]:
#a>20 # element by element comparison
#or
bool_arr = a>20
print(bool_arr) 

[[False  True False False False  True]
 [False False False  True  True False]
 [False False False False False  True]
 [False  True False  True  True  True]
 [False False False False False  True]]


In [93]:
ans = a[bool_arr]
print(ans)

[25 22 21 25 26 24 27 21 28 22]


In [94]:
b= a
b[bool_arr] = 100
print(b)

[[ 17 100   5  19  13 100]
 [ 10  20  15 100 100   4]
 [ 18   7   5   9  13 100]
 [ 11 100   6 100 100 100]
 [  9  12   5  14  13 100]]


In [95]:
c = np.random.randint(1,10,(2,2))
print(c)

[[1 9]
 [6 5]]


In [97]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


now learn about this error

In [98]:
print(c[c_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

in case of boolean arrays we have to make sure they are of same size and shape of our original array coz c is 2x2 and c_bool is 3x2

In [99]:
print(b)

[[ 17 100   5  19  13 100]
 [ 10  20  15 100 100   4]
 [ 18   7   5   9  13 100]
 [ 11 100   6 100 100 100]
 [  9  12   5  14  13 100]]


now chane only for 4th column


In [101]:
bool_arr = b[:,3] == 100
print(bool_arr)

[False  True False  True False]


#  numpy broadcasting