In [ ]:
import numpy as np
from PIL import Image

1. Remove those elements from one array that exist in another array? (without loop)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c1 = np.array(list(filter(lambda x: x not in a, b)))
c2 = np.array(list(filter(lambda x: x not in a, b)))
print(c1)
print(c2)

[6 7 8 9]
[6 7 8 9]


2. Get the positions where elements of 2 arrays match? (Without Loop)


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a==b))

(array([1, 3, 5, 7]),)


3. Reverse the rows of the nxn array? (Without Loop)


In [ ]:
a = np.array([[1,2,3,4], 
              [2,3,4,5], 
              [3,4,5,6], 
              [4,5,6,7]])

print(np.flip(a, axis=1))

[[4 3 2 1]
 [5 4 3 2]
 [6 5 4 3]
 [7 6 5 4]]


4. Normalize the values of the numpy array (i.e it means each element should be between 0 & 1 ) ? (without loop)

In [ ]:
a = np.array([26,34,32,16,33,27])
a = (a - a.min()) / (a.max() - a.min())
print(a)

[0.55555556 1.         0.88888889 0.         0.94444444 0.61111111]


5. Replace all the missing values of the numpy array with 0? (without loop)


In [ ]:
a = np.array([1,2,np.nan, 3,4,5, np.nan, 7, np.nan])
a[np.isnan(a)] = 0
print(a)

[1. 2. 0. 3. 4. 5. 0. 7. 0.]


6. Convert an Array of arrays to flat 1D array? (with loop and without loop)


In [ ]:
array_of_arrays = np.array([[0,1,2], [3,4,5], [6,7,8]])
array_of_arrays.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

7. Convert PIL Image to Numpy Array and Vice versa? (Important question and Do try it)

In [ ]:
a = Image.open('/BalloonImage.png')
print(type(a))

a = np.asarray(a)
print(type(a))

a = Image.fromarray(a.astype('uint8'), 'RGB')
print(type(a))

<class 'PIL.PngImagePlugin.PngImageFile'>
<class 'numpy.ndarray'>
<class 'PIL.Image.Image'>


8. Compute Euclidean Distance bw 2 arrays ? (without using inbuilt function i.e do not use np.linalg.norm)

In [ ]:
a = np.array([1, 0, 5])
b = np.array([0, 1, 5])

c = np.sqrt(np.sum(((a - b) ** 2)))
print(c)

1.4142135623730951
